In [2]:
# Abdul Qadir Boxwala
# 0801CS201003

# Q1. Write a NumPy program to compute the condition number of a given matrix.
import numpy as np

In [5]:
mat1=np.array([[1,2,3],[4,5,6],[1,2,3]])

In [6]:
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [8]:
print(np.linalg.cond(mat1))

5.125126400120226e+16


In [9]:
# Q2. Write a NumPy program to make all the elements of a given string to a numeric
# string of 5 digits with zeros on its left.
mat2=['2' ,'11' ,'234' ,'1234' ,'12345']

In [10]:
mat2=np.char.zfill(mat2,5)

In [11]:
mat2

array(['00002', '00011', '00234', '01234', '12345'], dtype='<U5')

In [12]:
# Q3. Perform all bitwise operations on array using numpy.
num1,num2=10,12

In [13]:
print(np.bitwise_and(num1,num2))  

8


In [14]:
print(np.bitwise_or(num1,num2))  

14


In [15]:
print(np.bitwise_xor(num1,num2))  

6


In [17]:
print(np.left_shift(num1,1))

20


In [18]:
print(np.right_shift(num1,1))

5


In [19]:
print("num1 = ",np.binary_repr(num1,width=8)," Inversion of num1 = ",np.binary_repr(np.invert(num1),width=8))

num1 =  00001010  Inversion of num1 =  11110101


In [37]:
#  Q4. Write a numpy program to display all the dates for the month of September 2022.
print(np.arange('2022-09', '2022-10',dtype='datetime64[D]'))

['2022-09-01' '2022-09-02' '2022-09-03' '2022-09-04' '2022-09-05'
 '2022-09-06' '2022-09-07' '2022-09-08' '2022-09-09' '2022-09-10'
 '2022-09-11' '2022-09-12' '2022-09-13' '2022-09-14' '2022-09-15'
 '2022-09-16' '2022-09-17' '2022-09-18' '2022-09-19' '2022-09-20'
 '2022-09-21' '2022-09-22' '2022-09-23' '2022-09-24' '2022-09-25'
 '2022-09-26' '2022-09-27' '2022-09-28' '2022-09-29' '2022-09-30']


In [21]:
# Q5. Apply all sorting techniques to sort the array along axis=1.Given array = ([ [34,
# 76, 18], [10, 56, 29], [52, 69, 77] ])
mat3=np.array([ [34,76, 18], [10, 56, 29], [52, 69, 77] ])

In [22]:
np.sort(mat3, axis=1,kind='quicksort') 

array([[18, 34, 76],
       [10, 29, 56],
       [52, 69, 77]])

In [23]:
np.sort(mat3, axis=1,kind='mergesort') 

array([[18, 34, 76],
       [10, 29, 56],
       [52, 69, 77]])

In [24]:
np.sort(mat3, axis=1,kind='heapsort') 

array([[18, 34, 76],
       [10, 29, 56],
       [52, 69, 77]])

In [25]:
np.sort(mat3, axis=1,kind='stable') 

array([[18, 34, 76],
       [10, 29, 56],
       [52, 69, 77]])

In [26]:
# Q6. Solve equation 4x+3y=20 and -5x+9y=26 find inverse of matrix,rank and also
# find cube of all elements.
# Like A=[[4,3][-5,9]] AND B=[20,26]
mat4=np.array([[4,3],[-5,9]])

In [27]:
mat5=np.array([20,26])

In [28]:
print(np.linalg.solve(mat4,mat5))

[2. 4.]


In [29]:
print(np.linalg.inv(mat4))

[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]


In [30]:
print(np.linalg.matrix_rank(mat4))

2


In [37]:
print(np.linalg.matrix_power(mat4,3))

[[-191  354]
 [-590  399]]


In [39]:
# Q7. Write a NumPy program to get the indices of the sorted elements of a given
# array(1023, 5202, 6230, 1671, 1682, 5241, 4532).
mat6=np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [40]:
print(np.argsort(mat6))

[0 3 4 6 1 5 2]


In [41]:
print(np.vstack((mat4,mat5)))

[[ 4  3]
 [-5  9]
 [20 26]]


In [42]:
print(np.hstack((mat4,mat4)))

[[ 4  3  4  3]
 [-5  9 -5  9]]


In [43]:
# Q8. Join array vertically and horizontally and find dimension and shape of array and
# also use reshape method .
print(np.ndim(mat4))

2


In [44]:
print(np.shape(mat4))

(2, 2)


In [45]:
print(np.reshape(mat4,(1,4)))

[[ 4  3 -5  9]]


In [46]:
# Q9. Find binomial and poisson distribution of array of size 20 and no of trials is 10.
print(np.random.binomial(10,0.1,20))

[1 1 0 1 0 1 1 3 1 1 1 2 0 0 0 1 0 0 1 0]


In [47]:
print(np.random.poisson(10,20))

[10  5  8 11 17  8 17 10 10  9 12 11  3 12  6 12 10 10 12 12]


In [48]:
# Q10. Write a NumPy program to test equal, not equal, greater equal, greater and less
# test of all the elements of two given arrays.
arr1,arr2=np.array([1,2,3]),np.array([4,5,6])

In [49]:
arr1,arr2

(array([1, 2, 3]), array([4, 5, 6]))

In [50]:
print(np.equal(arr1,arr2))

[False False False]


In [51]:
print(np.not_equal(arr1,arr2))

[ True  True  True]


In [52]:
print(np.greater_equal(arr1,arr2))

[False False False]


In [53]:
print(np.greater(arr1,arr2))

[False False False]


In [54]:
print(np.less(arr1,arr2))

[ True  True  True]


In [55]:
print(np.less_equal(arr1,arr2))

[ True  True  True]
